[FIX] Crash when sending bad accessType
esek/ekorre pull request #238
Opened 2022-08-30 09:54 UTC by blennster

2022-08-30 09:56 UTC, ginger51011 approved these changes
Lite fult men fine

2022-08-30 10:49 UTC, ginger51011 commented
> > Lite fult men fine
> 
> Hur hade du annars gjort?

Jag vet inte men känns bara fult att man försöker anropa API:n och bara carpet-kollar istället för kollar efter ett specifikt problem

2022-08-30 10:52 UTC, afroborg requested changes

2022-08-30 10:52 UTC, afroborg commented on src/routes/file.routes.ts
> +    const dbFile = await fileApi.saveFile(file, accessType, path, res.locals.user.username);
Vi kan ju checka att filetype finns i enumen istället? Och skicka en 400 ifall det är fel?

2022-08-31 08:47 UTC, afroborg approved these changes

2022-09-05 15:17 UTC, merged