Feat/events
esek/ekorre pull request #259
Opened 2023-04-03 17:38 UTC by Muncherkin

2023-04-03 17:50 UTC, ginger51011 requested changes
Not great, not terrible

But we should reconsider calling something `Utskott`; Firstly see #255, and also, `UTSKOTT` is already an enum

2023-04-03 17:50 UTC, ginger51011 commented on yarn.lock
We don't use yarn; Remove and stop using for `ekorre

2023-04-03 17:50 UTC, ginger51011 commented on src/schemas/orbi.graphql
> +    key: String!
What is `key`?

2023-04-03 17:50 UTC, ginger51011 commented on src/schemas/orbi.graphql
> +    getDepartments(departments: [Utskott]) : [UtskottInfo!]
We `Utskott` extensively; Don't mix. Departments is hard to understand

2023-04-03 17:50 UTC, ginger51011 commented on src/reducers/orbi.reducer.ts
> +    socials: {
Are socials link to the event? If yes, add a comment. If not, then why do we send and process it?

2023-04-03 17:50 UTC, ginger51011 commented on src/resolvers/orbi.resolver.ts
> +        ? await api.getDepartmentInfo(departments as Utskott[])
Don't use ternary expressions this way, very hard to read

2023-04-03 17:50 UTC, ginger51011 commented on src/resolvers/orbi.resolver.ts
> +        departments ? (departments as Utskott[]) : Object.values(Utskott),
This line gave me a strokkekelöakdöasfdäsa

2023-04-03 17:50 UTC, ginger51011 commented on src/schemas/orbi.graphql
> +type Socials{
What do these mean? Are they URLs to event, or E-sektionens social media? If it is the social media we should not return it here, or anywhere for that matter.

2023-04-03 17:50 UTC, ginger51011 commented on src/api/orbi.api.ts
> +export type OrbiActivityData = {
This should be in another file, like `models/` or `types/` or something, I don't remember

2023-04-03 17:50 UTC, ginger51011 commented on prisma/data/event.seed.ts
> +    description: "Vi gör inget intressant, almänt tråkigt smh...",
allmänt*

2023-04-03 17:50 UTC, ginger51011 commented on package.json
> +    "minio": "^7.0.32",
Why add this large dependency, what do we use it for?

2023-04-03 17:56 UTC, Muncherkin commented on src/reducers/orbi.reducer.ts
> +    socials: {
Each utskott has its own social links (if they care to add them). I'll add a comment

2023-04-03 18:10 UTC, Muncherkin commented on package.json
> +    "minio": "^7.0.32",
We don't hehe its for the new filesystem in the future. I'll remove it :))

2023-04-06 06:42 UTC, afroborg commented
Nice start! Just a little confused about this PR as it seems we are doing two different things? Are we adding both our own `events` that we handle in the DB as well as the Orbi integration? Could we not have just Orbi? - If so, I would say we call the orbi stuff `events` instead to make it more generic.

I'm thinking we add the orbi stuff as a `service` instead of calling it an `api`. Look at whats done with `wiki.service` or `email.service`. This is what we've done with external services, `api` is currently just used for stuff interacting with our own DB.

2023-04-06 06:44 UTC, afroborg commented on src/api/orbi.api.ts
> +const activitiesEndpoint = 'https://apis.orbiapp.io/v1/departments/activities';
You could create a new `axios` instance with `axios.create` like in `wiki.service` where we add `https://apis.orbiapp.io/v1/departments` as the `baseUrl`, then separate methods that call `/activities` and `/org-nodes/tree`

2023-04-06 06:47 UTC, afroborg commented on src/api/orbi.api.ts
> +    if (Date.now() - latestActivityResponse.timestamp < activityFetchCycle) return;
Instad of having this in memory, would it not be easier to pass the `from` and `interval` as parameters to the request (with reasonable default values)? This way each request can explicitly set what type of data it wants. The frontend would allow loading more and less.

2023-04-06 06:49 UTC, afroborg commented on src/api/orbi.api.ts
> +      return JSON.parse(String(res.data)) as OrbiActivityResponse;
axios should already return a json response, does it not? The `type` can be set by doing

```ts
const res = await axios.get<OrbiActivityRespone>(...);
```

2023-04-06 06:54 UTC, afroborg commented on src/resolvers/orbi.resolver.ts
> +    getActivities: async (_, { year: year, month: month, departments: departments }, __) => {
no need to assign `year: year` etc. in the destructuring, this is done implicitly.

2023-04-18 18:56 UTC, Muncherkin commented on yarn.lock
Removed. Sorry, I must have typed yarn into the terminal at some point. #EfterphestMoment

2023-04-18 18:58 UTC, Muncherkin commented on src/schemas/orbi.graphql
> +    getDepartments(departments: [Utskott]) : [UtskottInfo!]
Makes sense. Bit of swenglish but life do be like that. Should be written as "utskott" consistently now.

2023-04-18 18:59 UTC, Muncherkin commented on src/api/orbi.api.ts
> +export type OrbiActivityData = {
Moved into orbi.d.ts

2023-04-18 18:59 UTC, Muncherkin commented on prisma/data/event.seed.ts
> +    description: "Vi gör inget intressant, almänt tråkigt smh...",
Deleted the seed completely

2023-04-18 19:03 UTC, Muncherkin commented on src/api/orbi.api.ts
> +    if (Date.now() - latestActivityResponse.timestamp < activityFetchCycle) return;
I think this has been "resolved" or at least changed in the latest version of the branch.

2023-04-18 19:07 UTC, Muncherkin commented on src/api/orbi.api.ts
> +      return JSON.parse(String(res.data)) as OrbiActivityResponse;
Sort of. The result isn't of type `OrbiActivityResponse`, it's the `res.data` property which corresponds to the type. I might be really stupid but I'm not sure Orbi's public API is written well enough for me to figure out the JSON model that correlates to the return type. I can't seem to figure out all the fields. Possibly just printing out the return object in a console could work. 

Also, the response I get back is super weird. It should be JSON but then I get even more issues. Only solution I found was parsing it explicitly.

2023-04-18 19:08 UTC, Muncherkin commented on src/resolvers/orbi.resolver.ts
> +    getActivities: async (_, { year: year, month: month, departments: departments }, __) => {
Yeah my bad, changed now!

2023-04-18 19:23 UTC, Muncherkin commented on src/api/orbi.api.ts
> +const activitiesEndpoint = 'https://apis.orbiapp.io/v1/departments/activities';
Is it "taste-thing" as we say in the Sweden? True, this doesn't scale well with a lot more endpoints. I promise to revisit it.

2023-04-19 11:56 UTC, Muncherkin commented
Feat/events redo för merge. Se `CHANGELOG.md` för specifik info. Featuren är att skapa evenemang (kallas `activities` för att `event` kändes lite reserverat) på hemsidan och gruppera de med orbi-skapade evenamng. Dessa lagras i samma DB-table, `PrismaActivity`, som innehåller en referens till utskottet som håller i evenamnget, ett unikt id, en tag som säger att evenemanget är från orbi eller skapat på hemsidan och all information relevant för själva tillställningen (`about`, `desciption`, `title`, `location`, osv). 

Events kan raderas med mutaion `deleteActivity`, läggas till med mutation `addActivity` och query:as med `getActivities` med inparametrar för att hämta evenemang mellan datumen `from` och `to` samt endast från utskott som specificeras. Om inget utskott specas hämtas det från alla.

### Känt "problem"
Det går att radera orbi-baserade evenemang men de blir automagiskt tillagda igen nästa gång ett anrop görs till orbis API. En lösning är att lägga till en `blacklisted`-flagga i `PrismaActivity`. På så vis kan evenamng från orbi "raderas" genom att blacklistas. Om man vill ta bort evenemanget på rikitigt måste man radera det från orbi fullständigt. Jag ser ingen anledning att
göra detta just nu dock. Om ett evenamng finns på orbi kan det också finnas på hemsidan imo men man vill kunna välja kanske. Detta löser sig om vi implementerar feature:n nedan

### Framtida feature
Blacklisting/hiding: Att skapa och sen gömma evenemang kan vara en nice feature. Det blir mer flexibelt för den som anordnar evenamnget om man kan skapa eventet i sin egen tid men inte "reveala" evenemanget förens senare.

2023-04-25 20:43 UTC, ginger51011 commented on src/api/orbi.api.ts
Titel: :fire: Kodgranskning av OrbiAPI-kod :fire:

Jaha, här sitter jag igen och granskar er jävla sopkod. Stackars mig. Men låt oss gå igenom det här och se om vi kan göra något för att få det här skräpet att se mindre ut som något min katt hostade upp.

:poop: OrbiAPI-koden:

1. Vad fan är det här för röra med import? `@/models/orbi`, `@generated/graphql`, `@prisma/client`? Lär er något om jävla importstrukturer och gör det enklare att förstå var skiten kommer ifrån.

2. Sluta för helvete använda `new Axios()`! Använd `axios.create()` för att skapa en ny Axios-instans istället. Ni ser ut som jävla amatörer här.

3. Jävla hårdkodade konstanter överallt! Flytta ut dem till en konfigurationsfil istället för att ha dem spridda över hela koden som ett jävla fält av minröj. 

4. Döp om `defaultOrder` till något mer beskrivande, som t.ex. `defaultActivityOrder`. Var inte så jävla lata, det kostar inte mer att skriva några extra bokstäver.

5. I `updateActivities()`-metoden, använd `Date.now() - lastFetch >= fetchCycle` istället för `<`. Annars, om tiden mellan API-anropen är längre än `fetchCycle`, kommer ni att fortsätta göra fler anrop än nödvändigt. Ni borde ha lärt er det här redan, för fan.

6. Använd `async function getOrbiActs(n: number)` istället för `const getOrbiActs = async function (n: number)`. Det är en jävla funktion, så låt den se ut som en!

7. Använd mallsträngar istället för att konkatenera felmeddelanden som en jävla noob. Det är 2023, för fan, vi har haft mallsträngar i åratal nu. 

8. I `getDepartmentKeyTagMap()`, använd `axios.get<OrbiOrgTreeResponse[]>(OrgNodeEndpoint)` istället för att kasta om data till en sträng och sedan använda `JSON.parse`. Det är så jävla onödigt.

9. Sluta med de onödiga kommentarerna! Det är som att läsa en jävla roman när jag går igenom koden. Försök att göra koden självbeskrivande istället för att skriva en hel jävla uppsats om vad varje liten bit gör.

Lycka till med att rätta till det här skräpet, och kom ihåg att solen är din vän (även om ni inte ser den så ofta).

// Källarkungen :sunglasses: :crown:

2023-04-25 20:43 UTC, ginger51011 commented on src/api/activity.api.ts
Titel: :fire: Kodgranskning av ActivityAPI-kod :fire:

Okej, grabbar, nu kör vi igen! Hoppas ni är redo för en ännu mer brutal granskning av det här mästerverket av dålig kodning.

:poop: ActivityAPI-koden:

1. Ser ni vad jag ser? Återigen har vi här `defaultOrder`! Döp om den till något mer beskrivande, som t.ex. `defaultActivityOrder`. Det är för fan inte svårt.

2. Sluta exportera `OrbiAPI` direkt i `orbi.api` och skapa istället en ny instans i `ActivityAPI`. Så här:

   ```
   import { OrbiAPI } from './orbi.api';
   
   const orbiApi = new OrbiAPI();
   ```
   Annars kan ni inte garantera att den är oberoende av andra filer som kanske också importerar och skapar nya instanser.

3. Inuti `getActivities()`-metoden, vänta på att `orbiApi.updateActivities()` slutförs innan ni kör resten av koden. Just nu gör ni ett icke-väntande anrop, vilket kan skapa konstigheter. Använd `await` som så:

   ```
   await orbiApi.updateActivities();
   ```

4. I `removeActivity()`-metoden, använd `catch (err)` istället för att bara fånga alla fel. På det sättet kan ni logga rätt information och inte bara gissa vad som hände. Till exempel:

   ```
   catch (err) {
     logger.debug(`Could not delete activity with refKey ${id}: ${err}`);
     throw new ServerError('Kunde inte radera evenemanget, vilket kan bero på att det inte finns');
   }
   ```

5. Kolla här, prettier-ignore! Gör om radbrytningarna så att ni inte behöver den där fula kommentaren. Koden ser ut som något en kratta har dragits över.

6. Varför har ni en `clear()`-metod som bara raderar alla aktiviteter utan några kontroller? Det är en potentiell katastrof! Antingen lägg till någon form av kontroll eller ta bort den helt, så att ingen råkar förstöra all data.

Nu är det dags för er att krypa tillbaka till era små krypin och fixa det här skräpet. Och glöm inte att dricka lite D-vitamin för att kompensera för den sol ni aldrig ser.

// Källarkungen :sunglasses: :crown:

2023-04-25 20:43 UTC, ginger51011 commented on test/unit/activity.api.test.ts
Titel: :fire: Kodgranskning av testfilen :fire:

Okej, era kodbajsare, nu ska jag ge er några ord om det här testet ni har kläckt ur er. Håll i er för detta kommer bli en berg-och-dalbana av kodkritik.

:poop: Testfilen:

1. Importera `config` direkt från `'@/config'` istället för att använda en relativ sökväg. Det är så jävla fult och omodernt att jag får ont i ögonen.

2. Flytta `api = new ActivityAPI();` till en `beforeAll`-hook istället för en `beforeEach`-hook. Ni behöver inte skapa en ny instans av `ActivityAPI` för varje test, och det hjälper er att undvika onödiga API-anrop.

3. Sluta använda `if (config.ORBI.KEY.length === 0) { ... }` i varje test för att kolla om ni har en API-nyckel. Skapa en `beforeAll`-hook som gör kontrollen en gång och avbryter alla tester om API-nyckeln saknas:

   ```javascript
   beforeAll(() => {
     if (config.ORBI.KEY.length === 0) {
       console.log('aborting tests, no orbi api key specified');
       return;
     }
   });
   ```

4. Sätt en mer beskrivande titel för era tester. "adding and removing two events" låter som något ett barn skrev. Prova något i stil med "Testar att lägga till och ta bort två evenemang".

5. "Comparing non cached vs cached activity data speed"-testet känns inte som ett test, utan snarare en prestandamätning. Använd inte `test`-funktionen för det här ändamålet. Skapa en separat fil för att mäta prestanda om ni vill.

6. Försök att använda mer beskrivande variabelnamn. `event` och `event2` är riktigt dåliga val. Använd något som `event1Success` och `event2Success` istället.

Det var allt för den här gången, era kodbajsare. Gå nu och gödsla er kod med mina råd, så kanske den växer upp och blir något anständigt.

// Källarkungen :sunglasses: :crown:

2023-04-25 20:47 UTC, Muncherkin commented on src/api/orbi.api.ts
Tack för alla kloka punkter!

2023-04-25 20:48 UTC, Muncherkin commented on src/api/activity.api.ts
Helt rätt! Det ska jag lösa!

2023-04-25 20:48 UTC, ginger51011 commented on src/api/orbi.api.ts
😎👑

2023-04-25 20:55 UTC, Muncherkin commented on test/unit/activity.api.test.ts
Nu tror jag du har täckt allt! Väldigt rimlig kritik faktiskt! Mycket att lära sig med bara en månad+ Typescript och serverutveckling alls på nacken. 

Juste! En separat grej: Kanske ta och ändra din ton lite. Uppskattar också den "Linus Torvalds"-inspirerade jargongen du kör med, förstår att populärkulturen ser ut så för svettiga kodare som oss. Men å andra sidan, om du faktiskt vill att funktionärer i framtiden ska välja att engagera sig alls eller, du vet, undivka att genuint såra folk hade du nog behövt ta och fundera lite på det du väljer att skriva. I mean det är väl en nice alternativ att dö ensam i sin ekorre cesspit som alla andra har flytt från på grund av fruktansvärt omotiverande och trakasserande kommentarer. 

Tur att du är gammal och att jag inte råkade engagera mig i InfU 2021, jävlar va annorlunda mitt liv hade sett ut med dig i toppen av den näringskedjan <3

Aja, anyway, ska gå och utvärdera om jag känner mig bekväm med att komma på kodhackarkvällar i framtiden. Tror jag lägger orbi-projektet bakom mig ett tag i alla fall.

2023-04-25 21:24 UTC, ginger51011 reviewed
GPT-4 review without the

_Please write a code review for an imagined GitHub PR containing these pieces of code. You are role-playing as a basement dwelling nerd that does not see the sun often, using a lot of swearing to emphasize your points. You also speak swedish_

prompt

2023-04-25 21:24 UTC, ginger51011 commented on src/api/activity.api.ts
Hej där! Jag är en seniorutvecklare som snart ska lämna projektet och ville passa på att ge er lite feedback på er senaste PR. Först och främst vill jag säga att ni har gjort ett fantastiskt arbete! Jag ser mycket potential hos er unga och lovande utvecklare.

Här kommer några tankar och förslag på hur ni kan förbättra koden ytterligare:

1. Bra jobbat med att använda Prisma som ORM för att hantera kommunikationen med databasen. Det är en modern teknik som förenklar databashanteringen och gör koden mer lättläst och underhållbar.

2. Ni har implementerat felhantering med anpassade fel, som `ServerError`. Det är en utmärkt strategi, eftersom det ger mer meningsfulla meddelanden och gör det lättare att hantera fel på högre nivåer i applikationen.

3. Det är bra att ni använder en `Logger` för att logga viktiga händelser och fel i koden. Det underlättar felsökning och gör det lättare att förstå vad som händer i koden under körning.

4. En sak jag skulle rekommendera är att lägga till lite mer kommentarer i koden. Det hjälper både er och andra utvecklare att snabbt förstå syftet och funktionaliteten hos era funktioner och metoder.

5. I funktionen `getActivities` kontrollerar ni om `utskott` är tomt och tilldelar den `Object.values(Utskott)` om det är fallet. Det är ett effektivt sätt att hantera tomma parametrar och sätta standardvärden.

6. Kanske skulle ni kunna bryta ut den gemensamma logiken för att uppdatera aktiviteter från `getActivities` och `getAllActivities` till en separat metod. Det skulle göra koden mer DRY (Don't Repeat Yourself) och enklare att underhålla.

Sammantaget har ni gjort ett riktigt bra jobb med denna kod! Fortsätt utveckla era färdigheter och tveka inte att fråga om hjälp eller feedback längs vägen. Lycka till med ert fortsatta arbete på projektet!

2023-09-01 15:29 UTC, Muncherkin commented
Gonna make a new attempt

2023-09-01 15:29 UTC, closed without merging