Added SRE meeting types to db and graph
esek/ekorre pull request #264
Opened 2023-08-31 17:38 UTC by Muncherkin

SRE can now create meetings in `/admin/meetings` of type SRE grundnivå, SRE avancerad nivå and SRE intern and upload the minutes of the meetings which show up at `/about/meeting-documents` alongside guild meetings and board meetings.

2023-09-05 17:33 UTC, afroborg requested changes

2023-09-05 17:33 UTC, afroborg commented on package.json
> +    "Axel Anderssin <axel.so.andersson@gmail.com>"
Nice

2023-09-05 17:33 UTC, afroborg commented on src/reducers/meeting.reducer.ts
> +  const guildMeetings = [MeetingType.Htm, MeetingType.Vtm, MeetingType.Vm, MeetingType.Extra];
move this to the global scope instead so it's not redefined on every function call

2023-09-06 07:07 UTC, Muncherkin commented on src/reducers/meeting.reducer.ts
> +  const guildMeetings = [MeetingType.Htm, MeetingType.Vtm, MeetingType.Vm, MeetingType.Extra];
True and based. Did it!

2023-09-06 07:08 UTC, Muncherkin commented on package.json
> +    "Axel Anderssin <axel.so.andersson@gmail.com>"
I should know how to spell my last name I suppose. Oh well...

2023-09-06 08:19 UTC, afroborg approved these changes

2024-01-24 16:56 UTC, merged