Feature/hehe page
esek/ekorre pull request #272
Opened 2024-04-29 09:20 UTC by Studsministern

Changes:
- Adds extra Hehe functionality to ekorre that converts the cover page of a Hehe PDF into a PNG and saves it in the database. Also adds a new integration test to test this functionality

- Adds a unit test to check a file other than a PDF is not accepted for a Hehe

- Exposes the Hehe `uploadedAt` property as a `DateTime` so this can be used in the frontend

- Abstracts out functionality for uploading files in jest tests, and removing uploaded files, in both file- and Hehe tests

**Note**: This PR should be merged at the same time as a efterphest Hehe PR

2024-05-01 17:41 UTC, Studsministern commented
Do you also think the pagination is good enough for #241?

2024-05-05 11:03 UTC, pontussjostedt approved these changes
Tycker att det ser bra ut, har testat det tillsammans med frontenden och jag tycker det fungerar som jag förväntar mig.

2024-05-05 11:56 UTC, afroborg requested changes

2024-05-05 11:56 UTC, afroborg commented on src/api/hehe.api.ts
> +    for await (const page of document) {
any reason for doing this in a loop if we're just doing the first page? can't we just use document[0]?

2024-05-05 12:16 UTC, afroborg commented on src/schemas/hehe.graphql
> +  paginatedHehes(limit: Int!, offset: Int, sortOrder: SortOrder): [Hehe!]!
even though the implementation you have now works, we should go towards doing proper pagination from the start so we don't need to change it down the line. Meaning that the response of a paginated request should return the pagination metadata such as `totalCount` `hasNextPage` etc. see how we did it in [lager](https://github.com/esek/lager/blob/main/backend/graph/schemas/item.graphql) for example. Having this centralized will make it a lot easier down the line if all paginated requests look the same

2024-05-06 09:26 UTC, Studsministern commented on src/api/hehe.api.ts
> +    for await (const page of document) {
No. The `document` contains an `[Symbol.asyncIterator]()` attribute, which first needs to be accessed. Then the `next()` function must be called to get the first page. And finally the value must be checked so that it is actually a `Buffer`, and not a `void`. It would then look something like this:

```ts
// Gets the value
const coverPage = await document[Symbol.asyncIterator]().next();
const value = coverPage.value;

// Creates an UploadedFile if the value is not void
if (value) {
  const uploadedFile = this.createUploadedFile(value, coverName, 'image/png');
  const coverFile = await fileApi.saveFile(
    uploadedFile,
    accessType,
    COVER_FOLDER,
    uploaderUsername,
  );
  coverId = coverFile.id;
}
```

Which is a bit more complicated. The syntax I use is what is used in the [example provided by the package](https://www.npmjs.com/package/pdf-to-img).

So maybe better to keep it as it is?

2024-05-06 12:56 UTC, afroborg commented on src/api/hehe.api.ts
> +    for await (const page of document) {
Ouff alright, then yeah, your solution is much better!

2024-05-07 15:34 UTC, Studsministern commented on src/schemas/hehe.graphql
> +  paginatedHehes(limit: Int!, offset: Int, sortOrder: SortOrder): [Hehe!]!
Good point, I have started working on it!

However, I have one question:

I have gotten the backend to work reasonably well already. But in the process I discovered the use of a `directives.graphql` file in lager, where a `@nonNegative` directive is defined. This directive is then used in the `Pagination` type to make sure some fields are not allowed to be negative. Is this something that should be done in ekorre as well?

2024-05-07 17:44 UTC, afroborg commented on src/schemas/hehe.graphql
> +  paginatedHehes(limit: Int!, offset: Int, sortOrder: SortOrder): [Hehe!]!
Could be nice to look into, however not sure if necessary for a first iteration. We could add it to the backlog as this probably would be nice to have in other places as well! Just make sure to validate the params before you use them

2024-05-08 07:50 UTC, Studsministern commented on src/schemas/hehe.graphql
> +  paginatedHehes(limit: Int!, offset: Int, sortOrder: SortOrder): [Hehe!]!
Now I have implemented it!

However, I feel like there may be a better way to convert from `PrismaHehes` to `Hehes` than sending back a promise containing a list (`Promise<[PageInfo, PrismaHehe[]]>`) from `hehe.api.ts` to `hehe.resolver.ts`, and then creating the `PaginatedHehes` type. But I am unsure how:

```ts
paginatedHehes: async (_, { pagination }, ctx) => {
  await hasAuthenticated(ctx);
  const [pageInfo, hehes] = await heheApi.getHehesByPagination(pagination ?? undefined);
  return {
    pageInfo,
    values: reduce(hehes, heheReduce),
  };
},
```

Also, do you think there should also be a max page size, to determine how many items can be queried at once? I noticed lager had a max page size of 200, but to some extent I feel like it is the developer's task to determine a good amount for the specific implementation.

I also set the default page size to 20. I noticed lager used 50 as default, but I have a hard time determining if 20 or 50 (or something else) is the better choice for the type of data we store in ekorre. Maybe the `DEFAULT_PAGE_SIZE` should be moved from the `utils` file to the `.env`-file? Just like how `MAX_AVATAR_SIZE_MB` and `MAX_FILE_UPLOAD_SIZE_MB` are also set in this file?

2024-05-08 16:18 UTC, Studsministern commented
Thanks for the feedback @afroborg! Please see the final two comments above! :)

2024-05-28 20:01 UTC, Studsministern commented
The GitHub Action should be run again after the [pdf-to-png PR](https://github.com/esek/pdf-to-png/pull/1) has been merged, and after vault has been unlocked. A `PDF_TO_PNG_URL` environment variable probably also has to be set.

2024-05-31 08:22 UTC, merged