Feat/verify
esek/ekorre pull request #275
Opened 2024-09-09 08:58 UTC by Muncherkin

Added verification logic to user using a VerifyInfo object for future expansion.
Added connection to verify microservice.
Added automatic verification if user has a post.

!! - - This update is dependent on the same feature in Efterphest and Auth. - - !!

2024-09-10 09:12 UTC, afroborg commented on src/api/user.api.ts
> +    }
I feel like this should be extracted into a service to keep in line with how we're already doing services for other external api:s

2024-09-10 09:13 UTC, afroborg commented on src/resolvers/user.resolver.ts
> +      const posts = await postApi.getPostsForUser(username, false);
**Suggestion**
use Promise.all to fetch in parallell

2024-09-10 09:14 UTC, afroborg requested changes
add some tests for your new api functions pls

2024-09-11 12:28 UTC, Muncherkin commented on src/api/user.api.ts
> +    }
True!

2024-09-11 12:42 UTC, Muncherkin commented
Made changes after review!

2024-10-05 14:57 UTC, pontussjostedt approved these changes
This has been reviewed before :)

2024-10-05 14:58 UTC, pontussjostedt commented
LGTM! Reqest solved :)

2024-10-05 14:58 UTC, merged