Feature/accesslogs
esek/ekorre pull request #280
Opened 2024-10-19 12:07 UTC by pontussjostedt

Adds logs for setPostAccess and setIndividualAccess

2024-10-19 12:08 UTC, pontussjostedt commented on src/api/access.api.ts
> +  private getLogIndividualAccessDiffQuery(
A lot of code duplication between this and the Post access version. Might be better to just get the data for the query and make the query in the setIndividualAccess and setPostAccess methods

2024-10-19 12:11 UTC, pontussjostedt commented on prisma/schema.prisma
> +  grantor      PrismaUser         @relation(name: "PrismaPostAccessLogToPrismaUserGrantor", fields: [refGrantor], references: [username], onDelete: Cascade)
Unclear if we want the log to cascade delete or just be kept. It would be nice to not have to worry about nonexistent users when querying.

2024-10-21 09:45 UTC, Muncherkin commented on prisma/schema.prisma
> +  grantor      PrismaUser         @relation(name: "PrismaPostAccessLogToPrismaUserGrantor", fields: [refGrantor], references: [username], onDelete: Cascade)
Keep it as cascading, no one has any value in seeing logs that don't mean anything since they can't be used by anyone. Lowkey an automatic garbage collector and we love those.

2024-10-21 09:55 UTC, Muncherkin requested changes
Looks great! Please fix linting though, everything is screaming

2024-10-21 09:55 UTC, Muncherkin commented on src/api/access.api.ts
> +    for (const item of incoming) {
Not very common for us to use for loops in this way, should probably be done in some other manner, using promise.all

2024-10-21 09:55 UTC, Muncherkin commented on src/api/access.api.ts
> +    for (const item of current) {
Same here

2024-10-21 09:55 UTC, Muncherkin commented on src/api/access.api.ts
> +  private getLogIndividualAccessDiffQuery(
You can probably get the info by querying what access the user has against the access that is returned after granting someone access. I think this is fine though.

2024-10-21 09:55 UTC, Muncherkin commented on src/api/access.api.ts
> +      resourceType: 'door' as PrismaResourceType,
I believe `PrismaResourceType.door` will solve casting automatically, and maybe look at bit prettier.

2024-11-03 15:34 UTC, Muncherkin approved these changes
LGTM

2024-11-03 15:36 UTC, merged