Added hidden flag functionality to activities
esek/ekorre pull request #281
Opened 2024-12-23 21:49 UTC by Muncherkin

Made it possible to hide activities using a `hidden` flag. Also added functionality to query all activities including or excluding hidden ones.

2025-01-04 00:41 UTC, Muncherkin commented
JAG ÄR JESUS! DET ÄR LÖST! MERGEA MIG!

2025-01-04 10:10 UTC, afroborg requested changes

2025-01-04 10:10 UTC, afroborg commented on src/api/activity.api.ts
> +        ],
This is really hard to follow (and was already before this chaos so not only your fault). Not sure how we could make it better though so maybe just add some clarification because I don't really get how you want it to work?

We have the `hidden` flag, which is `required` in the graphql schema.
- If we send `hidden=true` do we only get the hidden events?
- Same with `hidden=false` for only the non-hidden events?

How would we go about getting all events if it's required in the schema?

2025-01-04 10:10 UTC, afroborg commented on src/schemas/activity.graphql
> +    hidden: Boolean
why does this need a hidden field?

2025-01-04 10:10 UTC, afroborg commented on src/schemas/activity.graphql
> +    hidden: Boolean
why does this need a hidden field?

2025-01-04 15:30 UTC, Muncherkin commented on src/api/activity.api.ts
> +        ],
I agree that it's completely unreadable, will change! The functionality is opposite to `current` on history queries:

hidden=false, only non hidden activities
hidden=true, all activities.

I'll change the name to `includeHidden`

2025-01-04 15:30 UTC, Muncherkin commented on src/schemas/activity.graphql
> +    hidden: Boolean
Do create an activity as hidden or not

2025-01-04 15:30 UTC, Muncherkin commented on src/schemas/activity.graphql
> +    hidden: Boolean
Do toggle an activity as hidden or not

2025-01-04 15:49 UTC, Muncherkin commented on src/api/activity.api.ts
> +        ],
Solved in latest commit

2025-01-04 17:24 UTC, Muncherkin commented
Reran the workflow but the Test annotations persisted even though the tests did actually work after the rerun

2025-01-15 18:06 UTC, Muncherkin commented on src/schemas/activity.graphql
> +    activities(from: DateTime!, to: DateTime!, utskott: [Utskott!]!, includeHidden: Boolean!) : [Activity!]!
Did this btw!

2025-01-15 18:07 UTC, merged